---
title: Setting Up a Lab Notebook
author: Ben Lorentz
date: '2022-10-04'
slug: setting-up-a-lab-notebook
draft: false
categories: []
tags: []
---
I wanted to find a little bit more elegant method to keeping notes from my various analyses. This notebook should hopefully help with this all. I am interested to see how it grows and evolves.

So far today I have worked on understanding the process of setting up, and rendering a blogdown document and pushing it up to the hosting server. As well as implementing a theme from GitHub. I think that this a stable enough solution to move forward with. 

### Other Tasks for today:

- watch lecture for class for Thursday (completed )
- check in on the ALDEx2 Analysis document to send to Shailes when it's done
  - [Link to commit](https://github.com/lorentzben/picrust2_shailes/commit/0ab89731173cf12d527517328967c6fe9753621a)
  - check in on tomorrow

Tomorrow's lecture was on short read sequencing and genome assembly topics included were:
  - Illumina Type sequencing
  - Quality control like FastQC to check for primers and low quality
  - Trimming of low quality sequences
  - OLC assembly
  - K-mer type assembly (SPADES)
  - Evaluation of assemblies (QUAST,BUSCO)
  

### Tasks for tomorrow: 
- See what the report for ALDEx2 looks like
- Continue working on the [pipeline to generate visualizations after ampliseq](https://github.com/lorentzben/ampliseqvis)

### Git commits:

#### Lorentz Notebook

```bash
e1f678f - Benjamin Lorentz, Wed Oct 5 15:42:08 2022 -0400 : add build rmd = true
6944b59 - Benjamin Lorentz, Wed Oct 5 15:41:18 2022 -0400 : had to re-add the theme
232f941 - Benjamin Lorentz, Wed Oct 5 15:39:29 2022 -0400 : had to re-add the theme
57bc276 - Benjamin Lorentz, Wed Oct 5 15:22:36 2022 -0400 : updated todays notes and added to cheatsheet
e6350a0 - Benjamin Lorentz, Wed Oct 5 15:10:31 2022 -0400 : change favicon in the template
142c739 - Benjamin Lorentz, Wed Oct 5 15:08:07 2022 -0400 : try to make cheatsheets show up in the right place
7b623c7 - Benjamin Lorentz, Wed Oct 5 15:05:22 2022 -0400 : mods to cheatsheets and about
a271985 - Benjamin Lorentz, Wed Oct 5 15:05:12 2022 -0400 : mods to cheatsheets and about
df6f29a - Benjamin Lorentz, Wed Oct 5 15:02:39 2022 -0400 : moved cheatsheets
b209676 - Benjamin Lorentz, Wed Oct 5 14:59:50 2022 -0400 : added public to gitignore
780548c - Benjamin Lorentz, Wed Oct 5 14:57:17 2022 -0400 : add git ignore
b648d60 - Benjamin Lorentz, Wed Oct 5 14:55:45 2022 -0400 : added new content
2f547bd - Benjamin Lorentz, Wed Oct 5 14:54:36 2022 -0400 : added updated links for homepage
d315c51 - Benjamin Lorentz, Wed Oct 5 14:53:39 2022 -0400 : added updated links for homepage
24786eb - Benjamin Lorentz, Wed Oct 5 14:39:25 2022 -0400 : update favicon
d367439 - Benjamin Lorentz, Wed Oct 5 14:32:52 2022 -0400 : modify the config.toml
ff1b155 - Benjamin Lorentz, Wed Oct 5 14:28:54 2022 -0400 : changed to hugo-tanka
```
#### picrust2_shailes:

```bash
0ab8973 - Benjamin Lorentz, Wed Oct 5 08:52:58 2022 -0400 : needed to generate the effect object for the larger glm
```