baseurl = "https://lorentznotebook.netlify.app/"
title = "Lorentz Lab Notebook"
author = "Benjamin Lorentz"
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"



enableEmoji = true
hasCJKLanguage = false

pygmentsstyle = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[params]
  sitename = "Lorentz Lab Notebook"  
  faviconfile = "images/favicon.png"
  highlightjs = true
  highlightjslanguages = ["r", "python", "stan"]
  uselatex = true
  progressively = false
# commentsrepo = "user/repo"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.primary]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.primary]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.primary]]
    name = "GitHub"
    url = "https://github.com/lorentzben"
    weight = 3
[[menu.primary]]
    name = "Google Scholar"
    url = "https://scholar.google.com/citations?user=3VhGECsAAAAJ&hl=en"
    weight = 4
[[menu.primary]]
    name = "ORCID"
    url = "https://orcid.org/0000-0002-9260-886X"
    weight = 5
[[menu.primary]]
    name = "Cheatsheets/Docs"
    url = "/cheatsheets/"
    weight = 6
[[menu.primary]]
    name = "Paper Notes"
    url = '/papers'
[[menu.primary]]
    name = "Archives"
    url = '/archives'
    
[permalinks]
    post = "/:year/:month/:day/:slug/"
    papers = "/:year/:month/:day/:slug/"
    
[taxonomies]
  tag = 'tags'

