[build]
command = "hugo"
publish = "public"
command = "hugo --gc --minify"

[build.environment]
HUGO_VERSION = "0.68.3"

[context]
[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"
[context.production]
[context.production.environment]
HUGO_ENV = "production"
HUGO_VERSION = "0.83.1"
HUGO_ENABLEGITINFO = "true"


[context.deploy-preview.environment]
  HUGO_VERSION = "0.83.1"
